VERSION=$(shell grep -oP "^__version__ = '\K([^'~]+)(?=')" motifapi/__init__.py | sed -r 's/-/~/g')
PKG_VERSION=0jrs1

FPM?=fpm
PYTHON?=python3

deb: python3-motifapi_${VERSION}-${PKG_VERSION}_all.deb

python3-motifapi_${VERSION}-${PKG_VERSION}_all.deb: $(MAKEFILE_LIST)
	$(FPM) --verbose --force \
		--maintainer "John Stowers <john.stowers@gmail.com>" \
		-s python -t deb \
		-n python3-motifapi \
		--no-python-dependencies \
		--python-internal-pip \
		--python-bin=${PYTHON} \
		--python-package-name-prefix=python3 \
		--version ${VERSION}-${PKG_VERSION} \
		-v ${VERSION}-${PKG_VERSION} \
		setup.py

clean:
	rm -f python3-motifapi_${VERSION}-${PKG_VERSION}_all.deb

.PHONY: clean
